<?php

//date_default_timezone_set('europe/kiev');
//echo date("d-m-Y H:i:s"); ?>

<?php $viewModelTwo = $this->getData('viewModel'); ?>
<?= $viewModelTwo->iAmViewModel() ?>

</br>
<span id="custom_time">Дата и время</span>
</br>

<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){

    function clock() {
        var d = new Date();
        var day = d.getDate();
        var hrs = d.getHours();
        var min = d.getMinutes();
        var sec = d.getSeconds();
        var mnt = new Array("января", "февраля", "марта", "апреля", "мая",
            "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря");
                if (day <= 9) day="0" + day;
                if (hrs <= 9) hrs="0" + hrs;
                if (min <=9 ) min="0" + min;
                if (sec <= 9) sec="0" + sec;

                $("#custom_time").html("Сейчас: " + hrs + ":" + min + ":" + sec + "&nbsp;&nbsp;&nbsp;" +
                    day + "-го " + mnt[d.getMonth()] + " " + d.getFullYear() + " г.");
            }
    setInterval(clock, 1000);

});

</script>

